
# Build Stage
FROM node:20-alpine AS build

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

# Copy source code
COPY . .

# Build-time env vars (Vite)
ARG VITE_BACKEND_URL
ARG VITE_ENV_MODE


ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_ENV_MODE=$VITE_ENV_MODE


# Build Vite app
RUN npm run build

#  Production Stage
FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Vite output directory is "dist"
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
