export const ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  DIRECTOR: "DIRECTOR",
  HOD: "HOD",
  REGISTRY: "REGISTRY",
  SUPERVISOR: "SUPERVISOR",
  OFFICER: "OFFICER",
  ARCHIVE: "ARCHIVE",
  ICT_ADMIN: "ICT_ADMIN",
};
