/**
 * Canonical AuditLog.action values for the auth module, kept in one place
 * so callers can't introduce typo'd/duplicate action strings.
 */
export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  LOGOUT_ALL: "LOGOUT_ALL",
  SESSION_REVOKED: "SESSION_REVOKED",
  TOKEN_REFRESH: "TOKEN_REFRESH",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_OTP_VERIFIED: "PASSWORD_RESET_OTP_VERIFIED",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  USER_CREATED: "USER_CREATED",

  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_DEACTIVATED: "DEPARTMENT_DEACTIVATED",
  DEPARTMENT_REACTIVATED: "DEPARTMENT_REACTIVATED",

  UNIT_CREATED: "UNIT_CREATED",
  UNIT_UPDATED: "UNIT_UPDATED",
  UNIT_DEACTIVATED: "UNIT_DEACTIVATED",
  UNIT_REACTIVATED: "UNIT_REACTIVATED",

  POSITION_CREATED: "POSITION_CREATED",
  POSITION_UPDATED: "POSITION_UPDATED",
  POSITION_DEACTIVATED: "POSITION_DEACTIVATED",
  POSITION_REACTIVATED: "POSITION_REACTIVATED",

  PERMISSION_CREATED: "PERMISSION_CREATED",
  PERMISSION_UPDATED: "PERMISSION_UPDATED",
  PERMISSION_DEACTIVATED: "PERMISSION_DEACTIVATED",
  PERMISSION_REACTIVATED: "PERMISSION_REACTIVATED",

  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DEACTIVATED: "ROLE_DEACTIVATED",
  ROLE_REACTIVATED: "ROLE_REACTIVATED",

  ROLE_PERMISSION_ASSIGNED: "ROLE_PERMISSION_ASSIGNED",
  ROLE_PERMISSION_REVOKED: "ROLE_PERMISSION_REVOKED",
  ROLE_PERMISSIONS_SYNCED: "ROLE_PERMISSIONS_SYNCED",

  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_ADMIN_UPDATED: "USER_ADMIN_UPDATED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_LOCKED: "USER_LOCKED",
  USER_UNLOCKED: "USER_UNLOCKED",
  USER_PASSWORD_RESET_BY_ADMIN: "USER_PASSWORD_RESET_BY_ADMIN",
  USER_ROLE_ASSIGNED: "USER_ROLE_ASSIGNED",
  USER_ROLE_REMOVED: "USER_ROLE_REMOVED",
};
